@MoneyApp.Server_HostAddress = https://localhost:7029

GET {{MoneyApp.Server_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MoneyApp.Server_HostAddress}}/user/login
Content-Type: application/json

{
  //LoginResquest
}

###

POST {{MoneyApp.Server_HostAddress}}/user/login
Content-Type: application/json

{
  //LoginResquest
}

###
